In [1]:
import random
import numpy as np

In [2]:
# randint to get a 3*3 matrix
l = [[random.randint(0, 10) for _ in range(3)] for _ in range(3)]
arr = np.array(l)
arr.shape

(3, 3)

In [3]:
# float to int
arr = np.array([1.1,2.2,3.3])
arr.astype("int32")

array([1, 2, 3], dtype=int32)

In [4]:
# even arr
arr = np.array([1,2,3,4,5,6])
arr = [item for item in arr if item%2==0]
arr

[np.int64(2), np.int64(4), np.int64(6)]

In [5]:
# reshape
arr = np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# boolean masking
arr = np.array([random.randint(0,101) for _ in range(10)])
arr = arr[arr>50]
arr

array([ 72,  93,  96, 100])